spring.application.name=simulador-transacciones

# H2 Database
spring.datasource.url=jdbc:h2:mem:simuladordb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JWT
jwt.secret=eglobal-simulador-secret-key-2026-very-long-and-secure-key-for-jwt
jwt.expiration=900000

#header secreto de mierda:
internal.api.secret=eglobal-internal-secret-2026